name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.0'

    - name: Lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.54

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
